### get clients
@serveur = http://localhost/serveur_api_rest

###
GET {{serveur}}/clients
Accept: application/json

### un client
GET {{serveur}}/client/1
Accept: application/json


### les salles
GET {{serveur}}/salles
Accept: application/json

### les salles
GET {{serveur}}/salle/3
Accept: application/json


### les salles
GET {{serveur}}/salle/4
Accept: application/json

### les salles
GET {{serveur}}/salle/5
Accept: application/json

### les offres
GET{{serveur}}/offers
Accept: application/json
